# Copyright (c) 2012-2018 Red Hat, Inc
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
---
kind: Template
apiVersion: v1
metadata:
  name: openshift-oauth-client
  annotations:
    description: Che
objects:
- apiVersion: v1
  kind: OAuthClient
  metadata:
    name: ${OCP_OAUTH_CLIENT_ID}
  secret: ${OCP_OAUTH_CLIENT_SECRET}
  redirectURIs:
    - ${REDIRECT_URI}
  grantMethod: prompt
parameters:
- name: REDIRECT_URI
  displayName: Redirect URI for OpenShift identity provider
- name: OCP_OAUTH_CLIENT_ID
  displayName: OAuth client ID
- name: OCP_OAUTH_CLIENT_SECRET
  displayName: OAuth client secret
